Front end
ssd-course-project/hotel pull request #2
Opened 2019-03-10 06:03 UTC by Cellofun

[Issue](https://github.com/ssd-course-project/hotel/issues/1)

2019-03-10 06:18 UTC, vladimirbokor commented
На сколько я понимаю, ` webpack-stats.json`, `node_modules/` надо добавить в gitignore

2019-03-10 06:39 UTC, Cellofun commented
@vladimirbokor мне казалось, я добавляла `node_modules/`. Исправлю.
Насчет `webpack-stats.json` и остального почитаю.

2019-03-13 15:05 UTC, vladimirbokor requested changes
мб так?

2019-03-13 15:05 UTC, vladimirbokor commented on project/settings.py
> +STATIC_ROOT = os.path.join(BASE_DIR, 'hotel/static')
Все же лучше разделить статику для проекта целиком и для конкретных приложений
```
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]
```

2019-03-13 15:05 UTC, vladimirbokor commented on project/settings.py
> +            os.path.join(BASE_DIR, 'hotel/templates/pug')
Зачем переопределять путь для конкретного приложения? Он же, вроде, по умолчанию будет искать в папке 'appsname'/templates

2019-03-13 15:05 UTC, vladimirbokor commented on project/settings.py
> +    'webpack_loader',
https://github.com/owais/django-webpack-loader если вот эту штуку юзала, то надо добавить ее в requirements 
 pip freeze > requirements.txt

и стоит в readme написать, как установить все, что касается фронта :)

2019-03-13 15:05 UTC, vladimirbokor commented on hotel/templates/index.html
> +{% load static %}<!DOCTYPE html>
А этот файл нужен вообще?

2019-03-14 05:35 UTC, Cellofun commented on project/settings.py
> +    'webpack_loader',
Ссылок на доки не достаточно?

2019-03-16 06:29 UTC, vladimirbokor approved these changes

2019-03-16 06:31 UTC, merged