T7 register front
ssd-course-project/hotel pull request #25
Opened 2019-04-19 09:12 UTC by AlenaOblozhenko

[](https://github.com/ssd-course-project/hotel/issues/7)

2019-04-19 16:11 UTC, Cellofun requested changes

2019-04-19 16:11 UTC, Cellofun commented on clients/templates/registration/login.html
> +            {% if form.errors %}<div class="register__error" >{{ form.errors }}</div> {% endif %}
Замени, пожалуйста, на это:

`{% if form.errors %}<div class="register__error" >{{ form.non_field_errors }}</div> {% endif %}`

2019-04-19 16:11 UTC, Cellofun commented on clients/templates/registration/login.html
> +{% endblock %}}
Нужно убрать последнюю фигурную скобку, чтобы стало так:

`{% endblock %}`

2019-04-19 16:11 UTC, Cellofun commented on clients/templates/registration/register.html
> +{% endblock %}}
Тоже нужно убрать последнюю фигурную скобку:

`{% endblock %}`

2019-04-19 16:11 UTC, Cellofun commented on clients/templates/registration/register.html
> +            {% if field.help_text %}<ul class="register__help" >{{ field.help_text }}</ul>  {% endif %}
Нужно заменить эту строку на:

`{% if field.help_text %}<div class="register__help" >{{ field.help_text|safe }}</div>{% endif %}`

2019-04-19 16:11 UTC, Cellofun commented on hotel/static/css/main.css
> +    color: #e75735; }
В файле `assets/sass/layouts/_l-register.scss` нужно заменить полностью блоки `&__help` и `&__error` на такое:

```
&__help {
    font-size: 0.75rem;
    font-weight: 300;
    ul {
      list-style: none;
    }
  }
  &__error {
    font-size: 0.75rem;
    font-weight: 300;
    color: $red;
    ul {
      list-style: none;
    }
  }
```

2019-04-19 16:11 UTC, Cellofun commented on hotel/static/css/main.css
> +    color: #e75735; }
Ну и соответственно сказать `yarn build`, не забыв после этого удалить файл `index.html` в папке `hotel/static`

2019-04-20 10:12 UTC, Cellofun requested changes

2019-04-20 10:12 UTC, Cellofun commented on hotel/static/css/main.css
> +    .register__error__label {
В `_l-register.scss` неверно вставлены `ul`, поэтому исчез класс `.register__label`, но появился несуществующий класс `.register__error__label.` После `&__button` нужно заменить на это:

```
&__help {
    font-size: 0.75rem;
    font-weight: 300;
    ul {
      list-style: none;
    }
  }
  &__error {
    font-size: 0.75rem;
    font-weight: 300;
    color: $red;
    ul {
      list-style: none;
    }
  }
  &__label {
    font-weight: 900;
    text-align: right;
  }
```

2019-04-20 12:44 UTC, Cellofun approved these changes

2019-04-20 18:01 UTC, vladimirbokor approved these changes

2019-04-20 18:01 UTC, merged