designed two pages
ssd-course-project/hotel pull request #40
Opened 2019-04-22 13:20 UTC by AlenaOblozhenko

(https://github.com/ssd-course-project/hotel/issues/26)
Страница "Контакты" и "Об отеле". Карту добавлять не стала, так как она есть на главной

2019-04-22 14:16 UTC, Cellofun requested changes

2019-04-22 14:16 UTC, Cellofun commented on hotel/templates/general/header.html
> +        <a class="header__item-link" href="{% url 'about_list' %}">об отеле</a>
Давай переименуем шаблон и имя на contacts и about соответственно? Для отеля и отзывов мы добавляли суффиксы, потому что были разные действия, например создание отзыва (feedback_new) и отображение списка (feedback_list).
Тут же действия единственные, поэтому можно вовсе не добавлять суффиксы.

2019-04-22 14:16 UTC, Cellofun commented on hotel/views.py
> +from idlelib.idle_test.test_help_about import About
Что это? Этого здесь быть не должно.

2019-04-22 14:16 UTC, Cellofun commented on hotel/views.py
> +    return render(request, 'hotel/contacts_list.html')
Давай перенесем статические странички в отдельную папку? Чтобы они не путались с основной функциональностью отеля.

2019-04-22 14:16 UTC, Cellofun commented on project/urls.py
> +    path('contacts/', include('django.contrib.auth.urls')),
А зачем дублировать урлы? Их нужно отсюда убрать.

2019-04-22 14:16 UTC, Cellofun commented on project/urls.py
> +from about import about
И это тоже нужно убрать.

2019-04-22 14:16 UTC, Cellofun commented on requirements.txt
> +about
Наверное, это очепятка :) Уберешь, пожалуйста?

2019-04-23 06:20 UTC, Cellofun approved these changes

2019-04-23 07:38 UTC, vladimirbokor approved these changes

2019-04-23 07:38 UTC, merged