T39 test room search view
ssd-course-project/hotel pull request #41
Opened 2019-04-23 07:52 UTC by Cellofun

[39](https://github.com/ssd-course-project/hotel/issues/39)

2019-04-23 12:13 UTC, vladimirbokor reviewed
Это тестирование на пустой базе, необходимо еще добавить пару номеров в setUp, и сравнить, что реально фильтрация работает, что в ответе лежат только нужные номера

2019-04-23 12:13 UTC, vladimirbokor commented on hotel/tests.py
> +        self.assertFalse(False, "Введите дату заезда и выезда")
Это что-то не то :)
здесь надо написать типо 
```
error_message = "" \
                "Введите дату заезда и выезда, чтобы мы могли показать вам " \
                "доступные в это время номера"

assert error_message == response.context_data.get('error_message')
или
self.assertEqual(error_message, response.context_data.get('error_message'))
```
второй вариант даже получше, только в 80 символов уложись :)

2019-04-23 12:13 UTC, vladimirbokor commented on hotel/tests.py
> +        self.assertTemplateUsed(response, "hotel/room_search.html")
Не знаю на сколько это важно проверять шаблон каждый раз на одинаковы запрос, но если нравится - можно оставить :)

2019-04-23 12:13 UTC, vladimirbokor commented on hotel/tests.py
> +        response = self.client.get("/rooms/", {"check_in_date": "2019-04-21", "check_out_date": "2019-04-25"})
80 символов :)

2019-04-23 12:13 UTC, vladimirbokor commented on hotel/tests.py
> +        self.assertTrue(True, response.content)
Тоже неправильное сравнение, ниже не буду уже писать про это

2019-04-25 09:08 UTC, AlenaOblozhenko approved these changes

2019-04-25 14:58 UTC, vladimirbokor reviewed
Тесты будут работать только для текущей даты, поэтому надо использовать контекстный менеджер         `with freeze_time("дата"):
`

2019-04-25 14:58 UTC, vladimirbokor commented on hotel/tests.py
> +        self.assertEquals([self.room1, self.room2], list(response.context['object_list']))
два момента:
1) Из словаря лучше всегда брать с помощью `get`, потому что он не бросит исключение, в случае если нет такого ключа.
2) Мне кажется, что тут не очень сравнение. Наверное, вот так будет лучше:
```
        self.assertQuerysetEqual(
            response.context.get('object_list'),
            map(repr, [self.room1, self.room2]),
            ordered=False
        )
```

2019-04-25 14:58 UTC, vladimirbokor commented on hotel/tests.py
> +        self.assertEqual(error_message, response.context_data.get('error_message'))
Кажется, ты поменяла это сообщение в другой ветке, которую уже вмержил в мастер. Там  `вам` было с большой буквы.

Ну и посмотри, чтоб в 80 символов все было, ниже уже не буду это писать :)

2019-04-25 14:58 UTC, vladimirbokor commented on hotel/tests.py
> +        self.assertEquals([self.room2], list(response.context['object_list']))
Такая же тема, как и выше :) не буду уже повторяться

2019-04-26 09:14 UTC, vladimirbokor requested changes

2019-04-26 09:14 UTC, vladimirbokor commented on hotel/tests.py
> +                        "доступные в это время номера"
80 символов :)

2019-04-26 09:14 UTC, vladimirbokor commented on hotel/tests.py
> +        with freeze_time("2019-04-21"):
Это надо делать перед запросом, сейчас тест не проходит

2019-04-26 09:14 UTC, vladimirbokor commented on hotel/tests.py
> +        self.assertEqual(error_message, response.context_data.get('error_message'))
В этом тесте тоже стоит проверить кверисет, копирни из `test_general_get_request`, он должен вернуть все комнаты

2019-04-26 13:27 UTC, vladimirbokor requested changes

2019-04-26 13:27 UTC, vladimirbokor commented on hotel/tests.py
> +from django.test import TestCase, Client
Client здесь лишний импорт :)

2019-04-26 13:30 UTC, vladimirbokor approved these changes

2019-04-26 13:31 UTC, merged