T38 test room status
ssd-course-project/hotel pull request #44
Opened 2019-04-28 18:15 UTC by AlenaOblozhenko

https://github.com/ssd-course-project/hotel/issues/38
Имеются несколько ошибок при запуске теста, пока не имею представления, как исправить

2019-04-28 18:28 UTC, Cellofun requested changes
Нужно вернуть картинки и откатить изменения из main.js

2019-04-28 19:00 UTC, Cellofun requested changes

2019-04-28 19:00 UTC, Cellofun commented on hotel/urls.py
> +    path('about/', views.about, name='about_list'),
Зачем это здесь? В мастере же уже есть эти страницы

2019-04-28 19:00 UTC, Cellofun commented on hotel/views.py
> +def about(request):
Тоже уже есть в мастере

2019-04-28 19:00 UTC, Cellofun commented on hotel/views.py
> +        if price:
Зачем? Это нужно убрать. Мы не фильтруем номера по статусу.

2019-04-28 19:00 UTC, Cellofun commented on hotel/tests.py
> +        client = Client.objects.create()
А где сам клиент? Нужно создать функцию `setUp`, в которой заранее создать пользователя и клиента, и потом использовать его в тестах. Можешь подсмотреть, как это сделала я.

2019-04-28 19:00 UTC, Cellofun commented on hotel/tests.py
> +            room=booked_room,
А где сам номер? Нужно создать его в `setUp`. ~~Можно посмотреть у меня в тесте~~

2019-04-28 19:00 UTC, Cellofun commented on hotel/tests.py
> +    def test_room_create(self):
Тесты ведь о проверке бронирования номера. Создание номера тестировать не нужно.

2019-04-28 19:00 UTC, Cellofun commented on hotel/tests.py
> +class RoomTest(TestCase):
Скорее `RoomBookingViewTest`

2019-04-28 19:00 UTC, Cellofun commented on hotel/tests.py
> +        room = Room.objects.filter(description="Заказанный номер")
Что это? Нужно ведь просто создать бронирование

2019-04-28 19:00 UTC, Cellofun commented on hotel/tests.py
> +        room_status = room.room_status(
Статус номера, который задается датами? У нас ничего подобного нет

2019-04-28 19:00 UTC, Cellofun commented on hotel/tests.py
> +        self.assertTrue(room_status == room.BOOKED_STATUS)
Это работает не так. Посмотри, пожалуйста, в моих тестах `self.assertQuerysetEqual`

2019-04-28 19:00 UTC, Cellofun commented on hotel/tests.py
> +    def test_room_available(self):
Все то же, что и для предыдущего теста

2019-04-29 06:41 UTC, AlenaOblozhenko commented on hotel/views.py
> +        if price:
ругался, что объект QuerySet не имеет атрибута room_status
и да, там заместо if price должно было быть if room_status

2019-04-29 06:45 UTC, Cellofun commented on hotel/views.py
> +        if price:
Так он ругался не потому, что во вью не было room_status, а от того, что в тесте его не должно быть

2019-04-29 07:11 UTC, AlenaOblozhenko commented on hotel/tests.py
> +        room = Room.objects.filter(description="Заказанный номер")
здесь проверяю, что номер точно занят в определенные даты

2019-04-29 07:14 UTC, Cellofun commented on hotel/tests.py
> +        room = Room.objects.filter(description="Заказанный номер")
Это делается не так. Посмотри, пожалуйста, тест `test_get_request_with_dates`.

2019-04-29 07:15 UTC, AlenaOblozhenko commented on hotel/tests.py
> +        room = Room.objects.filter(description="Заказанный номер")
хорошо, спасибо

2019-04-29 07:24 UTC, vladimirbokor commented on hotel/tests.py
> +        room = Room.objects.filter(description="Заказанный номер")
@AlenaOblozhenko, если в setUP создашь номер условно self.room,
то здесь будет достаточно вызвать метод `self.room.room_status(аргументы)`

2019-04-29 07:27 UTC, vladimirbokor commented on hotel/tests.py
> +        room_status = room.room_status(
Тут метод вызывается, так что это правильно :) а вот `desire_start_date` и `desire_finish_data` я не понял откуда

2019-04-29 07:28 UTC, vladimirbokor commented on hotel/tests.py
> +        self.assertTrue(room_status == room.BOOKED_STATUS)
Нене, конечный ассерт именно такой, тут все хорошо :)

2019-04-29 07:29 UTC, Cellofun commented on hotel/tests.py
> +        room_status = room.room_status(
Я имею в виду, у нас нет параметров `desire_start_date` и `desire_finish_date`

2019-04-29 12:31 UTC, AlenaOblozhenko commented
По-разному расписала аргументы:

2019-04-29 12:37 UTC, AlenaOblozhenko commented
По-разному расписала аргументы: 
Для def test_room_unavailable(self) : 
room_status = self.room.room_status(
                check_in_date=datetime.date(2019, 4, 21),
                check_out_date=datetime.date(2019, 4, 23)
            )
- выдает

2019-04-29 12:56 UTC, Cellofun reviewed
А файлы так и не вернулись :( Но их все равно нужно добавить

2019-04-29 12:56 UTC, Cellofun commented on hotel/urls.py
> +    path('contacts/', views.contacts, name='contacts_list'),
Контакты тоже уже есть в мастере

2019-04-29 12:56 UTC, Cellofun commented on hotel/views.py
> +def contacts(request):
Тоже самое, что в урлах

2019-04-29 13:04 UTC, AlenaOblozhenko commented
> И все равно нужно добавить

2019-04-29 18:33 UTC, closed without merging