added booking history and feedbacks for booking
ssd-course-project/hotel pull request #53
Opened 2019-05-05 12:59 UTC by AlenaOblozhenko

[20](https://github.com/ssd-course-project/hotel/issues/20)
Протестила, клиент без брони не может оставить отзыв

2019-05-05 15:46 UTC, vladimirbokor requested changes

2019-05-05 15:46 UTC, vladimirbokor commented on analytics/models.py
> +    )
Не из той таски, так же как и миграцию надо убрать отсюда

2019-05-05 15:46 UTC, vladimirbokor commented on analytics/views.py
> +    def dispatch(self, *args, **kwargs):
Почему именно `dispatch`? Он нужен чтоб делегировать запрос в зависимости от его типа. Тут тебе надо скорее гет запрос переписывать.

А с другой стороны возникает вопрос, зачем это? Если чтоб не давать админу создавать создавать отзывы - то нужно ставить проверку `user.is_superuser`. Если была другая цель - то напиши, пожалуйста

2019-05-05 15:46 UTC, vladimirbokor commented on analytics/views.py
> +        client = Client.objects.get(user=self.request.user)
Все гет метод надо оборачивать в try/except

2019-05-05 15:46 UTC, vladimirbokor commented on analytics/views.py
> +        if user and not any((user.is_superuser, user.is_staff)):
понял, что недостаточно проверки, есть ли юзер. нужно переписать это условие на:
`not any((user.is_superuser, user.is_staff, user.is_anonymous))`

Можно попросить тебя пройтись по всему проекту и где проверка на юзера, поменять ее на проверку на анонимного юзера в том числе.

2019-05-05 15:46 UTC, vladimirbokor commented on analytics/views.py
> +            context['client_has_made_booking'] = bookings.exists()
Так же как и выше, клиента обернуть в try/except, 
а строчку эту вот так можно сократить `context['client_has_made_booking'] = client.booking.all().exists()`

2019-05-05 15:46 UTC, vladimirbokor commented on clients/views.py
> +                client = Client.objects.get(user=user)
в try нужно класть только опасные операции, здесь нужно оставить только клиента, и обработку сделать, а не просто `pass`

2019-05-05 15:46 UTC, vladimirbokor commented on clients/views.py
> +                                                         | Q(check_out_date__lt=now))
`is_cancelled` из другой таски, рано еще сюда ее добавлять)

2019-05-05 15:46 UTC, vladimirbokor commented on hotel/templates/404.html~4e5d6c2eb79ce173c157e1350b3fa5f1300a5409
> +
Что это за файл?)

2019-05-05 16:31 UTC, AlenaOblozhenko commented on analytics/views.py
> +    def dispatch(self, *args, **kwargs):
Чтобы при попытке доступа пользователя без брони его переадресовало на список всех отзывов

2019-05-06 19:02 UTC, vladimirbokor requested changes

2019-05-06 19:02 UTC, vladimirbokor commented on analytics/views.py
> +        return client.booking.all().exists()
1. При таком коде, админ с фейковым аккаунтом и с бронированием все равно может создавать отзывы. Давай сделаем так, чтоб он не мог этого делать. Нужно написать типо
```
user = self.request.user
try:
  client = Client.objects.get(user=user)
except Client.DoesNotExist:
  return None

if any((not client, user.is_superuser, user.is_staff )):
        return False
else:
  client.booking.all().exists()
```

2. Функции, которые возвращают булевы значения лучше именовать вопросом. в данном случае `is_user_permitted_to_leave_feedback`

3. Лучше ее перенести в конец класса

2019-05-06 19:02 UTC, vladimirbokor commented on analytics/views.py
> +        if user and not any((user.is_superuser, user.is_staff, user.is_anonymous)):
Лишняя проверка на user

2019-05-06 19:02 UTC, vladimirbokor commented on analytics/views.py
> +                context['client_has_made_booking'] = False
Лучше вот так
```
 try:
     client = Client.objects.get(user=user)
except Client.DoesNotExists:
     сlient = None

context['client_has_made_booking'] = client.booking.all().exists() if client else False
```

2019-05-06 19:02 UTC, vladimirbokor commented on clients/views.py
> +from django.db.models import Q
Неиспользуемый импорт

2019-05-06 19:02 UTC, vladimirbokor commented on clients/views.py
> +import datetime
Лучше не импортировать весь модуль, а конкретную вещь из него
`from datetime import datetime`

2019-05-06 19:02 UTC, vladimirbokor commented on clients/views.py
> +            return context
Там ниже в по функции еще есть логика, а эта ее переписывает. Надо совместить их

2019-05-07 16:56 UTC, vladimirbokor requested changes

2019-05-07 16:56 UTC, vladimirbokor commented on analytics/models.py
> -
Верни пустую строчку

2019-05-07 16:56 UTC, vladimirbokor commented on analytics/views.py
> +        if not self.user_is_permitted_to_leave_feedback():
Функцию переименовала, а вызов нет

2019-05-07 16:56 UTC, vladimirbokor commented on analytics/views.py
> +            return None
не   `return None`, а client = None, ты же дальше его используешь

2019-05-07 16:56 UTC, vladimirbokor commented on analytics/views.py
> +            except Client.DoesNotExists:
не `DoesNotExists`, а `DoesNotExist`

2019-05-07 16:56 UTC, vladimirbokor commented on analytics/views.py
> +            context['client_has_made_booking'] = client.booking.all().exists() if client else False
80 символов

2019-05-07 16:56 UTC, vladimirbokor commented on analytics/views.py
> +            context['feedbacks'] = Feedback.objects.all()
Верни, пожалуйста, наследование от `ListView` с контекстом context_object_name = 'feedbacks'
Эту строчку удали, 
но надо будет еще написать 
```
    def get_queryset(self):
        return Feedback.objects.all().order_by('-created_at')
```

2019-05-07 16:56 UTC, vladimirbokor commented on clients/views.py
>              try:
здесь if уже не нужен этот

2019-05-07 16:56 UTC, vladimirbokor commented on clients/views.py
> +                if any((user.is_superuser, user.is_staff, user.is_anonymous)):
Зачем анонимному юзеру создавать клиента админа?

2019-05-07 16:56 UTC, vladimirbokor commented on clients/views.py
> +                    return context
Верни `None`, мы отсюда должны редиректить, через `render_to_response`

2019-05-08 11:07 UTC, vladimirbokor requested changes

2019-05-08 11:07 UTC, vladimirbokor commented on clients/templates/clients/profile.html
> +                {% for booking in bookings_archive %}
Здесь ты называешь ее `bookings_archive`, а в контекст кладешь `current_archive`. Как-то определиться надо :)

2019-05-08 11:07 UTC, vladimirbokor commented on clients/views.py
> +        context['current_archive'] = current_archive
давай добавим обоим `.order_by('-created_at') `

2019-05-08 11:07 UTC, vladimirbokor commented on clients/templates/clients/profile.html
> +                {% empty %}
Мм видимо надо позвать будет @Cellofun, потому что мне не очень нравится, как выглядит это 
![image](https://user-images.githubusercontent.com/35324009/57370809-4d255680-7191-11e9-8826-62cadb931fff.png)

2019-05-08 11:07 UTC, vladimirbokor commented on clients/templates/clients/profile.html
> +                {% empty %}
@Cellofun, можно отдельным МРом, наверное, сделать

2019-05-08 12:44 UTC, Cellofun commented on clients/templates/clients/profile.html
> +                {% empty %}
@vladimirbokor давай. Лучше после мержа логики в мастер или можно уже сейчас?

2019-05-08 14:38 UTC, vladimirbokor approved these changes

2019-05-08 14:39 UTC, merged